name: my_profile
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  url_launcher: ^6.1.5
  flutter_lints: ^2.0.0
  font_awesome_flutter: ^8.8.1

flutter:
  uses-material-design: true
  assets:
    - IMAGES/
  fonts:
    - family: DancingScripts
      fonts:
        - asset: fonts/DancingScript-VariableFont_wght.ttf
